name: djangoenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.20
  - pip=24.2
  - setuptools=75.1.0
  - wheel=0.44.0
  - pip:
      - asgiref==3.5.2
      - attrs==24.2.0
      - certifi==2024.8.30
      - config==0.5.1
      - django==4.1.3
      - djangorestframework==3.14.0
      - exceptiongroup==1.2.2
      - greenlet==3.1.1
      - h11==0.14.0
      - idna==3.10
      - mysql==0.0.3
      - mysqlclient==2.1.1
      - numpy==2.0.2
      - outcome==1.3.0.post0
      - pandas==2.2.3
      - pymysql==1.1.1
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2022.6
      - selenium==4.25.0
      - six==1.16.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.36
      - sqlparse==0.4.3
      - trio==0.27.0
      - trio-websocket==0.11.1
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - websocket-client==1.8.0
      - wsproto==1.2.0
