# Generated by Django 4.1.3 on 2024-10-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0002_alter_major_unique_together"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="major",
            table="major_subject",
        ),
    ]
