# Generated by Django 4.1.3 on 2024-10-30 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_alter_major_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkkuSubject',
            fields=[
                ('degree_courses', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_field3', models.CharField(blank=True, max_length=100, null=True)),
                ('course_code', models.CharField(max_length=100)),
                ('course_title', models.CharField(max_length=100)),
                ('course_title_english', models.CharField(max_length=100)),
                ('instructor', models.CharField(blank=True, max_length=100, null=True)),
                ('campus', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_field2', models.CharField(blank=True, max_length=100, null=True)),
                ('credit', models.CharField(max_length=100)),
                ('classtime', models.TextField(blank=True, null=True)),
                ('type_of_class1', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_class2', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('semester', models.CharField(max_length=100)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_field', models.CharField(blank=True, max_length=100, null=True)),
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'skku_subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fix',
            fields=[
                ('fix_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=100)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.skkusubject')),
            ],
            options={
                'db_table': 'fix',
            },
        ),
        migrations.DeleteModel(
            name='LiberalArts',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
    ]
